version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./templates:/app/templates
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped